package com.peluqueria.entity;


public enum TiposServicio {
    PEINADO,
    PEINADO_RECOGIDO,
    CORTE_ESTILO,
    CORTE_FEMENINO,
    CORTE_MASCULINO,
    COLOR_COMPLETO,
    COLOR_RAICES,
    MECHAS,
    CAMBIO_ESTILO_COLOR,
    CAMBIO_FORMA_PERMANENTE,
    TRATAMIENTO
}
